import eslint from '@eslint/js';
import prettierConfig from 'eslint-config-prettier';

// Globals available to the extension's browser-context sources.
const browserGlobals = {
  chrome: 'readonly',
  window: 'readonly',
  document: 'readonly',
  console: 'readonly',
  location: 'readonly',
  setTimeout: 'readonly',
  clearTimeout: 'readonly',
  setInterval: 'readonly',
  clearInterval: 'readonly',
  requestAnimationFrame: 'readonly',
  cancelAnimationFrame: 'readonly',
  queueMicrotask: 'readonly',
  fetch: 'readonly',
  URL: 'readonly',
  URLSearchParams: 'readonly',
  Blob: 'readonly',
  File: 'readonly',
  FileReader: 'readonly',
  FormData: 'readonly',
  Image: 'readonly',
  navigator: 'readonly',
  indexedDB: 'readonly',
  getComputedStyle: 'readonly',
  alert: 'readonly',
  confirm: 'readonly',
  atob: 'readonly',
  btoa: 'readonly',
  TextEncoder: 'readonly',
  TextDecoder: 'readonly',
  crypto: 'readonly',
  structuredClone: 'readonly',
  globalThis: 'readonly',
  performance: 'readonly',
  MutationObserver: 'readonly',
  ResizeObserver: 'readonly',
  IntersectionObserver: 'readonly',
  DOMParser: 'readonly',
  XMLSerializer: 'readonly',
  HTMLElement: 'readonly',
  Element: 'readonly',
  Node: 'readonly',
  NodeList: 'readonly',
  Event: 'readonly',
  CustomEvent: 'readonly',
  MouseEvent: 'readonly',
  KeyboardEvent: 'readonly',
  Response: 'readonly',
};

// Globals for the Node build/config scripts.
const nodeGlobals = {
  require: 'readonly',
  module: 'writable',
  exports: 'writable',
  process: 'readonly',
  __dirname: 'readonly',
  __filename: 'readonly',
  Buffer: 'readonly',
  console: 'readonly',
};

export default [
  {
    ignores: [
      'node_modules/',
      'dist/',
      'coverage/',
      // Build outputs (generated by build.cjs — do not lint generated code):
      'js/background.js',
      'js/pintwist-catalog-shared.js',
      'popup.js',
    ],
  },
  eslint.configs.recommended,
  prettierConfig,
  {
    files: [
      'catalog.js',
      'catalog-utils.js',
      'catalog-db.js',
      'catalog-store.js',
      'popup-catalog.js',
      'src/**/*.js',
    ],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      globals: browserGlobals,
    },
    rules: {
      'no-empty': ['error', { allowEmptyCatch: true }],
      'no-unused-vars': ['warn', { argsIgnorePattern: '^_', varsIgnorePattern: '^_' }],
      // CSV/text sanitizers legitimately match control characters (e.g. stripping \x00–\x1f).
      'no-control-regex': 'off',
      'prefer-const': 'error',
      'no-var': 'error',
    },
  },
  {
    // The large hand-maintained content script. It is NOT a module (top-level
    // `function` declarations + 'use strict'), and the perf-hotfix block uses a
    // decorator pattern that intentionally reassigns those declarations across
    // IIFEs to wrap/override them — so rules that fight that pattern are relaxed,
    // while the bug-catching rules from eslint:recommended (no-undef, no-dupe-keys,
    // no-unreachable, no-cond-assign, …) stay on.
    files: ['js/content.js'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'script',
      globals: { ...browserGlobals, history: 'readonly', getSelection: 'readonly' },
    },
    rules: {
      // Reassigning function declarations to wrap/override them IS the architecture here.
      'no-func-assign': 'off',
      // Base impls the hotfix reassigns (and cross-IIFE bridges) read as "unused".
      'no-unused-vars': ['warn', { argsIgnorePattern: '^_', varsIgnorePattern: '^_' }],
      // CSV/text sanitizers legitimately match control characters.
      'no-control-regex': 'off',
      'no-empty': ['error', { allowEmptyCatch: true }],
    },
  },
  {
    files: ['build.cjs'],
    languageOptions: { ecmaVersion: 2022, sourceType: 'commonjs', globals: nodeGlobals },
  },
  {
    files: ['eslint.config.js'],
    languageOptions: { ecmaVersion: 2022, sourceType: 'module', globals: nodeGlobals },
  },
];
